
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Appli/CMake/share/cmake-3.26/Modules/CMakeDetermineSystem.cmake:204 (message)"
      - "CMakeLists.txt:1 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Appli/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Appli/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Appli/CMake/share/cmake-3.26/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:1 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.6.3+07e294721 for .NET Framework
      La génération a démarré 13/12/2023 11:48:57.
      
      Projet "C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.vcxproj" sur le noud 1 (cibles par défaut).
      PrepareForBuild:
        Création du répertoire "Debug\\".
        Création du répertoire "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Création de "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TC /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X64 Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Suppression du fichier "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Mise à jour de l'horodatage "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Génération du projet "C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\3.26.4\\CompilerIdC\\CompilerIdC.vcxproj" terminée (cibles par défaut).
      
      La génération a réussi.
          0 Avertissement(s)
          0 Erreur(s)
      
      Temps écoulé 00:00:01.02
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Users/Eleve/Documents/GitHub/Bataille_Navale/Bataille_Navale/CMakeFiles/3.26.4/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Appli/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Appli/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Appli/CMake/share/cmake-3.26/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:1 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      MSBuild version 17.6.3+07e294721 for .NET Framework
      La génération a démarré 13/12/2023 11:48:59.
      
      Projet "C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" sur le noud 1 (cibles par défaut).
      PrepareForBuild:
        Création du répertoire "Debug\\".
        Création du répertoire "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Création de "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
      ClCompile:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /nologo /W0 /WX- /diagnostics:column /Od /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc143.pdb" /external:W0 /Gd /TP /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X64 Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\Hostx64\\x64\\cl.exe
      FinalizeBuildStatus:
        Suppression du fichier "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Mise à jour de l'horodatage "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Génération du projet "C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\3.26.4\\CompilerIdCXX\\CompilerIdCXX.vcxproj" terminée (cibles par défaut).
      
      La génération a réussi.
          0 Avertissement(s)
          0 Erreur(s)
      
      Temps écoulé 00:00:00.67
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Users/Eleve/Documents/GitHub/Bataille_Navale/Bataille_Navale/CMakeFiles/3.26.4/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Appli/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Appli/CMake/share/cmake-3.26/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:1 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Users/Eleve/Documents/GitHub/Bataille_Navale/Bataille_Navale/CMakeFiles/CMakeScratch/TryCompile-d4tj2r"
      binary: "C:/Users/Eleve/Documents/GitHub/Bataille_Navale/Bataille_Navale/CMakeFiles/CMakeScratch/TryCompile-d4tj2r"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/Eleve/Documents/GitHub/Bataille_Navale/Bataille_Navale/CMakeFiles/CMakeScratch/TryCompile-d4tj2r
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_17b4c.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.6.3+07e294721 for .NET Framework
        La génération a démarré 13/12/2023 11:48:59.
        
        Projet "C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\CMakeScratch\\TryCompile-d4tj2r\\cmTC_17b4c.vcxproj" sur le noud 1 (cibles par défaut).
        PrepareForBuild:
          Création du répertoire "cmTC_17b4c.dir\\Debug\\".
          Création du répertoire "C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\CMakeScratch\\TryCompile-d4tj2r\\Debug\\".
          Création du répertoire "cmTC_17b4c.dir\\Debug\\cmTC_17b4c.tlog\\".
        InitializeBuildStatus:
          Création de "cmTC_17b4c.dir\\Debug\\cmTC_17b4c.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_17b4c.dir\\Debug\\\\" /Fd"cmTC_17b4c.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Appli\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
          Compilateur d'optimisation Microsoft (R) C/C++ version 19.36.32535 pour x64
          CMakeCCompilerABI.c
          Copyright (C) Microsoft Corporation. Tous droits réservés.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_17b4c.dir\\Debug\\\\" /Fd"cmTC_17b4c.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TC /errorReport:queue "C:\\Appli\\CMake\\share\\cmake-3.26\\Modules\\CMakeCCompilerABI.c"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\CMakeScratch\\TryCompile-d4tj2r\\Debug\\cmTC_17b4c.exe" /INCREMENTAL /ILK:"cmTC_17b4c.dir\\Debug\\cmTC_17b4c.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/Eleve/Documents/GitHub/Bataille_Navale/Bataille_Navale/CMakeFiles/CMakeScratch/TryCompile-d4tj2r/Debug/cmTC_17b4c.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Eleve/Documents/GitHub/Bataille_Navale/Bataille_Navale/CMakeFiles/CMakeScratch/TryCompile-d4tj2r/Debug/cmTC_17b4c.lib" /MACHINE:X64  /machine:x64 cmTC_17b4c.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_17b4c.vcxproj -> C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\CMakeScratch\\TryCompile-d4tj2r\\Debug\\cmTC_17b4c.exe
        FinalizeBuildStatus:
          Suppression du fichier "cmTC_17b4c.dir\\Debug\\cmTC_17b4c.tlog\\unsuccessfulbuild".
          Mise à jour de l'horodatage "cmTC_17b4c.dir\\Debug\\cmTC_17b4c.tlog\\cmTC_17b4c.lastbuildstate".
        Génération du projet "C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\CMakeScratch\\TryCompile-d4tj2r\\cmTC_17b4c.vcxproj" terminée (cibles par défaut).
        
        La génération a réussi.
            0 Avertissement(s)
            0 Erreur(s)
        
        Temps écoulé 00:00:00.60
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Appli/CMake/share/cmake-3.26/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Appli/CMake/share/cmake-3.26/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:1 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Users/Eleve/Documents/GitHub/Bataille_Navale/Bataille_Navale/CMakeFiles/CMakeScratch/TryCompile-xndkos"
      binary: "C:/Users/Eleve/Documents/GitHub/Bataille_Navale/Bataille_Navale/CMakeFiles/CMakeScratch/TryCompile-xndkos"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: C:/Users/Eleve/Documents/GitHub/Bataille_Navale/Bataille_Navale/CMakeFiles/CMakeScratch/TryCompile-xndkos
        
        Run Build Command(s):C:/Program Files/Microsoft Visual Studio/2022/Community/MSBuild/Current/Bin/amd64/MSBuild.exe cmTC_3581a.vcxproj /p:Configuration=Debug /p:Platform=x64 /p:VisualStudioVersion=17.0 /v:n && MSBuild version 17.6.3+07e294721 for .NET Framework
        La génération a démarré 13/12/2023 11:49:00.
        
        Projet "C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\CMakeScratch\\TryCompile-xndkos\\cmTC_3581a.vcxproj" sur le noud 1 (cibles par défaut).
        PrepareForBuild:
          Création du répertoire "cmTC_3581a.dir\\Debug\\".
          Création du répertoire "C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\CMakeScratch\\TryCompile-xndkos\\Debug\\".
          Création du répertoire "cmTC_3581a.dir\\Debug\\cmTC_3581a.tlog\\".
        InitializeBuildStatus:
          Création de "cmTC_3581a.dir\\Debug\\cmTC_3581a.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
        ClCompile:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\CL.exe /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_3581a.dir\\Debug\\\\" /Fd"cmTC_3581a.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Appli\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
          Compilateur d'optimisation Microsoft (R) C/C++ version 19.36.32535 pour x64
          CMakeCXXCompilerABI.cpp
          Copyright (C) Microsoft Corporation. Tous droits réservés.
          cl /c /Zi /W3 /WX- /diagnostics:column /Od /Ob0 /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_3581a.dir\\Debug\\\\" /Fd"cmTC_3581a.dir\\Debug\\vc143.pdb" /external:W3 /Gd /TP /errorReport:queue "C:\\Appli\\CMake\\share\\cmake-3.26\\Modules\\CMakeCXXCompilerABI.cpp"
        Link:
          C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.36.32532\\bin\\HostX64\\x64\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\CMakeScratch\\TryCompile-xndkos\\Debug\\cmTC_3581a.exe" /INCREMENTAL /ILK:"cmTC_3581a.dir\\Debug\\cmTC_3581a.ilk" /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Users/Eleve/Documents/GitHub/Bataille_Navale/Bataille_Navale/CMakeFiles/CMakeScratch/TryCompile-xndkos/Debug/cmTC_3581a.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Users/Eleve/Documents/GitHub/Bataille_Navale/Bataille_Navale/CMakeFiles/CMakeScratch/TryCompile-xndkos/Debug/cmTC_3581a.lib" /MACHINE:X64  /machine:x64 cmTC_3581a.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_3581a.vcxproj -> C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\CMakeScratch\\TryCompile-xndkos\\Debug\\cmTC_3581a.exe
        FinalizeBuildStatus:
          Suppression du fichier "cmTC_3581a.dir\\Debug\\cmTC_3581a.tlog\\unsuccessfulbuild".
          Mise à jour de l'horodatage "cmTC_3581a.dir\\Debug\\cmTC_3581a.tlog\\cmTC_3581a.lastbuildstate".
        Génération du projet "C:\\Users\\Eleve\\Documents\\GitHub\\Bataille_Navale\\Bataille_Navale\\CMakeFiles\\CMakeScratch\\TryCompile-xndkos\\cmTC_3581a.vcxproj" terminée (cibles par défaut).
        
        La génération a réussi.
            0 Avertissement(s)
            0 Erreur(s)
        
        Temps écoulé 00:00:00.60
        
      exitCode: 0
...
